namespace EnterpriseAssistant.Core.Models.Dashboard;

/// <summary>
/// Business Logic:
/// Represents a dashboard activity
/// event generated by Enterprise Assistant.
/// </summary>
public sealed class ActivityFeedItemDto
{
    /// <summary>
    /// Activity timestamp.
    /// </summary>
    public DateTime Timestamp { get; set; }

    /// <summary>
    /// Activity description.
    /// </summary>
    public string Message { get; set; } = string.Empty;
}